## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [2]:
n = 10
a = np.array([1, 2, 3] * n)
print(a)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [3]:
a = np.linspace(1, 19, 10, dtype = np.int32)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [4]:
a = np.zeros((10,10), dtype = np.int32)
a[::9] = 1
a[::,::9] = 1
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [5]:
a = np.zeros((8,8), dtype = np.int32)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [6]:
n = 5

def matrix_create(n):
    z = np.indices((n,n))
    z.shape
    return z[0] + z[1]

print(matrix_create(n))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [7]:
n = 10
vector = np.random.randint(1, 101, n)
matrix = np.random.randint(1, 101, (n, n))
print(f'vector: {vector} \nmatrix:\n {matrix} \n')

print(f'matrix * matrix:\n {np.dot(matrix, matrix)} \n\n vector * vector: {np.dot(vector, vector)} \
\n\n vector * matrix: {np.dot(vector, matrix)}')

vector: [12 93 51 99 91 36 41 36 53 58] 
matrix:
 [[ 6 35 34 82 77 71 88 13  6 12]
 [ 7 49 37 70 36 48 90 52  3  6]
 [89  8  9 20 11 67 62 47 43 64]
 [45 56 76 16 80 91 95 11 93 42]
 [88 77 31 60 76 24 70 61 45 45]
 [43 99 63 35 81 93 13  5 73 62]
 [81 73 75 31 97  1 82 54 56 14]
 [75 38 56 79 96  8 45 68 66 58]
 [23 51  3 29 47  1 23 36 83 18]
 [44 12 95  4 31 57 28 58 76 77]] 

matrix * matrix:
 [[25595 27115 23383 16016 30697 21179 28164 15998 25073 16787]
 [23583 23157 22085 16713 28983 17877 27071 16436 22591 15074]
 [18492 21452 22976 18501 29634 19750 22631 15026 23198 16477]
 [31606 33592 25725 24050 36992 25484 33615 24242 32394 22530]
 [27506 28952 27624 28060 38565 24705 38708 24179 27945 19723]
 [25095 29870 24086 23554 31151 29464 31510 21725 28782 22583]
 [30242 27378 22228 28091 35827 20890 38930 25565 25119 18305]
 [30862 27474 26835 26147 37816 25099 37713 25142 32117 23074]
 [13510 16166 12120 14871 19759  9562 18777 14005 17226  9459]
 [25916 20190 20542 18229 26401 

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [8]:
t = np.arange(0, 1, 0.05)
print(f'matrix:\n {np.vstack([np.sin(t), np.cos(t)])}')

matrix:
 [[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155 ]
 [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [9]:
a = np.random.uniform(-1, 3, (3, 5))
print(a)

[[ 2.91683296  0.76726122  2.26296267  1.27517252  1.08094564]
 [ 2.07344769  0.98651378  2.89859164  0.33637309 -0.45209818]
 [ 2.58021342  0.77762848  0.72742128 -0.51698463  0.45696697]]


In [10]:
print(f'matrix:\n {a} \n')

print(f'columns sum: {np.sum(a, axis = 0)} \nlines sum: {np.sum(a, axis = 1)} \nmatrixs sum: {np.sum(a)} \
\ndispersion: {np.var(a, axis = 1)} \naverage value: {np.mean(a, axis = 1)} \nstandard deviation: {np.std(a, axis = 1)}')

matrix:
 [[ 2.91683296  0.76726122  2.26296267  1.27517252  1.08094564]
 [ 2.07344769  0.98651378  2.89859164  0.33637309 -0.45209818]
 [ 2.58021342  0.77762848  0.72742128 -0.51698463  0.45696697]] 

columns sum: [7.57049408 2.53140348 5.88897559 1.09456097 1.08581442] 
lines sum: [8.303175   5.84282801 4.02524553] 
matrixs sum: 18.171248542850236 
dispersion: [0.64471395 1.43280801 1.00538414] 
average value: [1.660635   1.1685656  0.80504911] 
standard deviation: [0.80294081 1.19699959 1.00268846]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [21]:
print(f'original matrix:\n {a} \n\nresult:\n {(a - np.repeat(np.mean(a, axis = 1), 5).reshape(3,5)) / np.repeat(np.std(a, axis = 1), 5).reshape(3,5)}')

original matrix:
 [[ 2.91683296  0.76726122  2.26296267  1.27517252  1.08094564]
 [ 2.07344769  0.98651378  2.89859164  0.33637309 -0.45209818]
 [ 2.58021342  0.77762848  0.72742128 -0.51698463  0.45696697]] 

result:
 [[ 1.56449634 -1.11262719  0.75015202 -0.48006338 -0.72195778]
 [ 0.75595857 -0.15209013  1.44530212 -0.69523208 -1.35393847]
 [ 1.77040466 -0.0273471  -0.07741968 -1.31848904 -0.34714884]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [12]:
print(f'original matrix:\n {a} \n\nmatrix was sorted by 3rd column:\n {a[a[:, 2].argsort()]}')


original matrix:
 [[ 2.91683296  0.76726122  2.26296267  1.27517252  1.08094564]
 [ 2.07344769  0.98651378  2.89859164  0.33637309 -0.45209818]
 [ 2.58021342  0.77762848  0.72742128 -0.51698463  0.45696697]] 

matrix was sorted by 3rd column:
 [[ 2.58021342  0.77762848  0.72742128 -0.51698463  0.45696697]
 [ 2.91683296  0.76726122  2.26296267  1.27517252  1.08094564]
 [ 2.07344769  0.98651378  2.89859164  0.33637309 -0.45209818]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [22]:
b = np.dot(a.T, a)
c = np.dot(a, a.T)
print(f'matrix b:\n {b} \n\nmatrix c:\n {c}')
'''
Матрицы B и C
'''

matrix b:
 [[19.46460118  6.28990498 14.48766442  3.08298654  3.39460822]
 [ 6.28990498  2.16660527  5.16144759  0.90820513  0.73871711]
 [14.48766442  5.16144759 14.05197526  3.4846104   1.4680991 ]
 [ 3.08298654  0.90820513  3.4846104   2.00648492  0.99007361]
 [ 3.39460822  0.73871711  1.4680991   0.99007361  1.58165504]] 

matrix c:
 [[17.01211277 13.30445917  9.6035348 ]
 [13.30445917 13.99176788  7.84508239]
 [ 9.6035348   7.84508239  8.26744102]]


'\nМатрицы B и C\n'

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [103]:
print(f'b diagonal sum: {np.trace(b)} \nc diagonal sum: {np.trace(c)}')

b diagonal sum: 104 
c diagonal sum: 104


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [23]:
print(f'determinant of a: {np.linalg.det(a)} \nrank of a: {np.linalg.matrix_rank(a)} \ndeterminant of b: {np.linalg.det(b)} \
\nrank of b: {np.linalg.matrix_rank(b)} \n\neigenvalues of b:\n {np.linalg.eig(b)} \n \
\ndeterminant of c: {np.linalg.det(c)} \nrank of c: {np.linalg.matrix_rank(c)} \n\neigenvalues of c:\n {np.linalg.eig(c)}')

LinAlgError: Last 2 dimensions of the array must be square

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [12]:
np.random.seed(1032201725)
print(np.random.randint(9))

h = 0.00001
x = np.arange(0, 2, h)
n = len(x)

f = (2 * x - 1) / (2 * x + 1)

rectangel = h * np.sum(f)

trapezoid = (h / 2) * (f[0] + 2 * np.sum(f[1:n - 1]) + f[n-1])

simpsons = (h / 3) * (f[0] + 2 * np.sum(f[2:n - 2: 2]) + 4 * np.sum(f[1: n - 1: 2]) + f[n - 1])


print(f'rectangels method: {rectangel} \ntrapezoids method: {trapezoid} \nsimpsons: {simpsons} \n')


8
rectangels method: 0.39055408753389975 
trapezoids method: 0.3905560875418998 
simpsons: 0.3905500876032333 

